baseURL = 'https://mickey991.gitee.io/emacs-latex'
languageCode = 'en-us'
title = '金色飞贼小米的主页'

theme = "PaperMod"
[markup.goldmark.renderer]
	unsafe = true

[params]
	math = true
	ShowCodeCopyButtons = true
	showtoc = true
