baseURL: "https://mickey991.gitee.io/"
# languageCode: "zh"
defaultContentLanguage : "zh"
title: "金色飞贼小米的主页"

     
theme: "PaperMod"

## markup.goldmark.renderer:
##  unsafe: true 

params:
  math: true
  ## code
  ShowCodeCopyButtons: true

  ## toc
  showtoc: true
  tocopen: true
  UseHugoToc: true

  ## additional info
  ShowPostNavLinks: true
  ShowWordCount: true
  ShowReadingTime: true

  ## layout
  ShowBreadCrumbs: true

  ## use chroma for markup
  assets:
    disableHLJS: true

menu:
  main:
    - identifier: home
      name: 主页
      url: /
      weight: 1
    - identifier: LaTeX
      name: LaTeX
      url: /ELatex/
      weight: 10
    - identifier: PKM
      name: 个人知识库
      url: /PKM/
      weight: 20
    - identifier: bilibili
      name: B站主页
      url: https://space.bilibili.com/314984514
      weight: 30

## use chroma for syntax highlighting
markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # noClasses: false
    style: monokai
