baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[markup.goldmark.renderer]
  unsafe = true

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"


theme = "PaperMod"