#+title: 从零搭建Emacs个人知识库之 Zotero文献管理系统简介

在视频 [[https://www.bilibili.com/video/BV1qV4y1Z7h9/][【从零搭建Emacs个人知识库】什么是双链笔记与 org-roam 初体验]] 中, 我们介绍了个人知识库与卡片盒笔记的基本概念. 卢曼的卡片盒笔记系统大致将笔记分为3类: 灵感笔记, 文献笔记与永久笔记. 我们的学习和科研也离不开大量文献的阅读. 因此, 如何在我们的笔记系统中加入与文献或文献笔记的联系就至关重要. 今天我将给大家一款简单实用的文献管理软件: =Zotero=. =Zotero= 可以帮助我们收集文献的引用信息, 以及管理文献的 =pdf= 全文. 下一期我们将介绍如何把 Zotero 整合到 =org-roam= 的工作流程中. 我使用 =Zotero= 也有10年时间了, 这绝对是一个对科研帮助很大的工具. 

* 历史
=Zotero= 原本是火狐 (Firefox) 浏览器中的一个插件, 用于从网页上读取文献信息或保存网络快照等, 在火狐上可以直接使用, 而在其它浏览器上需要配合浏览器插件. 2017 年 =Zotero 5.0= 发布, =Zotero= 成为一个独立的软件. 在所有浏览器中使用都需要同时运行 =Zotero=.

* 安装
=Zotero= 和它的浏览器插件 (=Zotero Connector=) 都可以从它的[[https://www.zotero.org/download/][官网]]上下载. =Zotero= 的PC端支持 Windows, MacOS, Linux 等系统, 移动端暂时只支持苹果系统, 但在安卓上有第三方软件. 浏览器插件支持 Edge, Chrome, Safari 以及 Firefox 等主流浏览器. 

* 基本使用方法
=Zotero= 的界面从左至右分为3部分. 中间是文献列表, 右边是当前选中文献的信息, 包括标题, 作者等. 具体的信息类型会根据文献的类别, 如期刊文献, 书藉, 网页, 学位论文等, 而有所有不同. 最左边是用户自己设置的收藏夹 (collection), 可以嵌套, 用于文献的整理和分类. 

同一个文献可以出现在多个不同的收藏夹. 把文献加入收藏夹的方式很简单: 用鼠标拖动文献至指定的收藏夹即可.
这里有一个小技巧, 按住 ~<ctrl>~ 并点击文献, 左边一栏就会高亮文献出现的所有收藏夹.

除了按照主题分类文献外, 我也常会把同一研究课题相关的文献放在同一个收藏夹. 当需要撰写课题相关的论文时, 可以使用 =Zotero= 的导出功能, 将同一个收藏夹内的参考文献信息导出成 =.bib= 文件. 如果不用 =LaTeX= 进行写作, 也可以导出成其它常见格式用于论文写作. 导出文献非常灵活, 你也可以 选中任意数目的文献, 然后鼠标右键菜单中选择导出即可.

文献可以有附件, 一般是 =pdf=. 这里的 =pdf= 文件既可以是下载文献信息时 =Zotero= 自动下载的, 也可以是你手动添加的. 当文献有 =pdf= 附件时, 只要双击就能在 =Zotero= 的内置 =pdf= 阅读器内打开. 最新的 =pdf= 阅读器效果还是很不错的, 可以高亮批注等等, 也可以与 =Zotero= 其它文献阅读功能配合, 当然我们最终会使用 =Emacs= 中的 =org-noter= 来进行文献阅读. 你也可以设置用电脑上其它的 =pdf= 阅读器打开 =pdf= 的默认阅读器.
* 向 Zotero 中加入文献
=Zotero= 的强大就在于它加入文献的方式非常灵活. 主要用下面3种方式.
1. 通过浏览器中的 =Zotero Connector= 插件
2. 通过文献的标识码
3. 通过本地的 =pdf= 文件

在第一种方法中, 打开任意包含文献的网站 (最好是期刊官网), 点击 =Zotero= 插件的图标就可以自动读取网页上的文献信息. 
如果网站上允许下载 =pdf= 全文, =Zotero= 还会自动下载. 对于普通网页, =Zotero= 默认会保存网页快照. 这在10年前网速和流量短缺时是一很有用的功能, 可以在有限的时间内快速保存网页以便以后阅读, 如今用处不大了.

第二种方法支持的标识码包括 =DOI=, =ISBN=, =Arxiv ID= 等. 点击 =Zotero= 文献列表上左起第二个画笔的小图标, 输入标识码, 就可以自动下载文献和 =pdf= 文件.

这里推荐大家尽量使用前两种方式下载, 因为这样可以保证你在论文写作时, 所引用的参考文献的信息是准确无误的. 这里首要是保证文献信息的来源准确. 当你有了文献信息后, 也可 c 通过其它手段下载 =pdf= 全文, 然后在 =Zotero= 中用右键点击文献, 选择添加 =pdf= 附件 (attachment).

如果实在不得已, 你也可以采用第三种方法: 手动从本地的 =pdf= 文件创建一个文献条目. 方法是点击文献列表上左起第一个绿色的加号, 选择 =Store copy of file=. =Zotero= 会尝试从 =pdf= 文件中读取文献的信息并生成一个文献条目. 

我们在使用中重复添加一个文献是很常见的, 比如说你可能几年前找过这个文献, 但你忘记了, 后来又在做另一个课题的时候碰到了. 在 =Zotero= 中有一个很方便的功能, 可以快速整合不同版本的文献信息. 点击左侧收藏夹最下面的 =Duplicate Items=, 就会显示文献库中所有重复的条目. 我们可以手动选择保留哪一个版本的标题, 作者, 期刊信息等, 然后选择 =Merge=, 将不同版本的文献合并成同一个条目.
* 功能小结
总结起来, Zotero 实现了如下核心功能
- 收集并整理文献信息
- 根据需要导出文献引用信息
- 管理文献 =pdf=

因为 =Zotero= 还有一个强大的生态, 所以它的功能远不止上面介绍的这些. 我平时使用更多是把 =Zotero= 作为个人资料库里文献管理的一个入口, =Zotero= 的其它功能也可以在 =Emacs= 中更好地实现. 但是在这里还是要向大家介绍两个非常实用的 =Zotero= 插件: =Better BibTeX= 和 =ZotFile=.

=Better BibTeX= 可以优化导出 =.bib= 文件时引用键名的生成, 还可以对导出的 =.bib= 文件实时更新. 它也是 =Zotero= 与其它笔记软件, 如 =Org-Roam=, =Obsidian=, =Roam Research= 等进行交互的必备插件.

=ZotFile= 补充了一些 =pdf= 文件管理的功能. 它可以自动对 =pdf= 附近按自定义规则重命名, 并用个人网盘同步, 解决 =Zotero= 的同步问题.

* 插件安装方法
要安装 =Zotero= 插件, 我们首先在它的插件网站上下载对应的 =.xpi= 格式文件, 然后打开 =Tools= ->  =add-ons= , 选择从文件进行安装即可. 

* =Better BibTex= 设置
=Better BibTex= 的设置在 =Edit= -> =Preference= 下.

首先修改引用键名的格式. 比如这里我推荐的一个设置是 ~authorsAlpha+year+shorttitle(3,3)~
- =authorsAlpha=: 采用 =bibtex= 中的 =alpha= 风格; 单作者取姓的前3字母, 2个以上取首字母
- =year=: 4位数字年份
- =shorttitle(m,n)=: 标题前 m 个单词, 其中前 n 个单词首字母大写
大家可以在 https://retorque.re/zotero-better-bibtex/citing/ 中找到更多的设置
键名设置的原则是在突出重要信息的前提下尽量简短. 也方便有时我们直接在 =pdf= 文件目录进行搜索 (如在手机和平板上).

第二, 为了保证键名的唯一性, 大家可以在下面勾选 =across all libraries=.

最后, 我们可以设置 =Better BibTeX= 自动更新导出的 =.bib= 文件. 当我们选中一个收藏夹并且导出时, 选择 =Better BibTeX= 格式, 并且勾选下面的 "自动更新". 然后, 我们在 =Better BibTeX= 的设置的 =Automatic Export= 这一页就可以看到刚刚导出的 =.bib= 文件了. 我们可以把更新的频率选为 =On change=, 即随时更新. 

* =Zotfile= 同步设置
在 =Edit= -> =Preference= -> =Sync= 下面, 大家可以注册并登录 =Zotero= 帐号实现不同设备间的同步. 但是 =Zotero= 的免费空间只有500M, 这对于 =pdf= 文件的同步是不够的. 所以建议大家用下面介绍的 =ZotFile= 同步 =pdf= 附件, 而让 =Zotero= 只负责同步文献信息.

 =Better BibTeX= 的键名无法同步, 但是只要规则相同, 产生的键名是一样的. 在新机器上建议大家先设置好 =Better BibTeX= 的键名规则, 再登录 =Zotero= 帐号同步文献信息. 如果已经同步了文献信息, 则需要手动更新所有的 =Better BibTeX= 键名, 大的文献库需要几分钟的时间. 

下面我们讲解 =Zotfile= 的设置. 设置界面在 =Tools= -> =ZotFile Preference= 菜单下.

第一步,  我们设置在 =General Settings= -> =Custom Locations= 下设置一个同步目录. 这里你可以设置为个人网盘里一个子目录. 下面还有一个是否使用子文件夹的选项, 没必要勾选, 因为子文件夹不方便搜索, 而且 =Zotero= 本身的收藏夹功能已经对文献做好分类了. 存储时没必要再分一次类.

第二步, 我们给 =ZotFile= 设置一个统一的命名规则, 用于给新添加的 =pdf= 文件重命名. 设置在 =Renaming Rules= 下面. 这里推荐使用 ~%b~,  即采用了之前 =BibTeX= 的键名作为文件名.
步, 因为 =ZotFile= 可以自动给 所以我们要设置一个d. 利于我们在不同机器上的使用.  这样设置也可以方便笔记软件在读取 =.bib= 文件时能通过键名更快地找到对应的 =pdf= 文件. 也方便我们自己的查打.

最后, 我们在 =Advanced Settings= -> =automatically rename new attachment= 中选择 =alwasy rename=. 这样可以对对 =Zotero= 自动下载的 =pdf= 文件自动重命名并移动至我们的个人网盘中.  如果你是手动加入的 =pdf= 文件, 也可以手动重命名并移动 =pdf= 文件. 方法是右键点击文献条目, 选择 =rename and move= .
* 结语
以上就是 =Zotero= 的基本设置. 下次我们会介绍如何在 =org-roam= 笔记流程中整合 =Zotero=, 包括
- =Emcas= 中读取 =Zotero= 文献数据库并进行引用
- 每一条引用的 =Zotero= 文献建立一则 =org-roam= 笔记
- 将上述笔记作为 =org-noter= 笔记文件, 在 =Emacs= 中阅读 =Zotero= 文献的 =pdf= 附件

关于 =org-roam= 和 =org-noter= 大家可以参考我的视频 [[https://www.bilibili.com/video/BV1qV4y1Z7h9/][BV1qV4y1Z7h9]] 与 [[https://www.bilibili.com/video/BV1Tc411s7Tu/][BV1Tc411s7Tu]].   


