(setq cdlatex-command-alist
      '(("eq" "insert pairs of \\[ \\]" "\\[ ? \\]" cdlatex-position-cursor nil t t)
        ("exe" "Insert exercise" "\\begin{exercise}
       ?
       \\end{exercise}" cdlatex-position-cursor nil t nil)
        ("ons" "" "\\onslide<?>{ }" cdlatex-position-cursor nil t t)
        ("prop" "insert proposition" "" cdlatex-environment ("proposition") t nil)
        ("aali" "insert equation" "\\left\\{\\begin{aligned}
                 ?
                 \\end{aligned}\\right." cdlatex-position-cursor nil nil t)
        ("te" "insert text" "\\text{?}" cdlatex-position-cursor nil nil t)
        ("st" "stackrel" "\\stackrel{?}{}" cdlatex-position-cursor nil nil t)
        ("fra" "insert frame (for beamer)" "" cdlatex-environment ("frame") t nil)
        ("lr<" "insert bra-ket" "\\langle ? \\rangle" cdlatex-position-cursor nil nil t)
        ("spl" "insert split" "" cdlatex-environment ("split") nil t)
        ("equ*" "insert unlabel equation" "" cdlatex-environment ("equation*") t nil)
        ("ipite" "insert in paragraph itemize" "" cdlatex-environment ("inparaitem") t nil)
        ("ipenu" "insert in paragraph enumerate" "" cdlatex-environment ("inparaenum") t nil)
        ("des" "insert description" "" cdlatex-environment ("description") t nil)
        ("lem" "insert lemma env" "" cdlatex-environment ("lemma") t nil)
        ("thm" "insert theorem env" "" cdlatex-environment ("theorem") t nil)
        ("pro" "insert proof env" "" cdlatex-environment ("proof") t nil)
        ("def" "insert definition env" "" cdlatex-environment ("definition") t nil)
        ("liml" "insert \\lim\\limits_{}" "\\lim\\limits_{?}" cdlatex-position-cursor nil nil t)
        ("prodl" "insert \\prod\\limits_{}^{}" " \\prod\\limits_{?}^{}" cdlatex-position-cursor nil nil t)
        ("cupl" "insert \\bigcup\\limits_{}^{}" "\\bigcup\\limits_{?}^{}" cdlatex-position-cursor nil nil t)
        ("capl" "insert \\bigcap\\limits_{}^{}" "\\bigcap\\limits_{?}^{}" cdlatex-position-cursor nil nil t)
        ("big(" "insert big ()" "\\big( ? \\big" cdlatex-position-cursor nil nil t)
        ("Big(" "insert Big ()" "\\Big( ? \\Big" cdlatex-position-cursor nil nil t)
        ("bigg(" "insert bigg()" "\\bigg( ? \\bigg" cdlatex-position-cursor nil nil t)
        ("big|" "insert big|" "\\big| ? \\big|" cdlatex-position-cursor nil nil t)
        ("Big|" "insert Big|" "\\Big| ? \\Big|" cdlatex-position-cursor nil nil t)
        ("bigg|" "insert bigg|" "\\bigg| ? \\bigg|" cdlatex-position-cursor nil nil t)
        ("Big\\|" "insert Big \\|" "\\Big\\| ? \\Big\\|" cdlatex-position-cursor nil nil t)
        ("bigg\\|" "insert bigg\\|" "cdlatex-position-cursor" cdlatex-position-cursor nil nil t)
        ("case" "insert cases" "" cdlatex-environment ("cases") nil t)
        ("big\\|" "insert big \\|" "\\big\\| ? \\big\\|" cdlatex-position-cursor nil nil t)
        ("se" "insert \\{\\}" "\\{ ? \\}" cdlatex-position-cursor nil nil t)
        ("big{" "insert big {}" "\\big\\{ ? \\big\\" cdlatex-position-cursor nil nil t)
        ("big[" "insert big []" "\\big[ ? \\big" cdlatex-position-cursor nil nil t)
        ("Big{" "insert Big{}" "\\Big\\{ ? \\Big\\" cdlatex-position-cursor nil nil t)
        ("bigg{" "insert bigg{}" "\\bigg\\{ ? \\bigg\\" cdlatex-position-cursor nil nil t)
        ("Big[" "insert Big[" "\\Big[ ? \\Big" cdlatex-position-cursor nil nil t)
        ("bigg[" "insert bigg[" "\\bigg[ ? \\bigg" cdlatex-position-cursor nil nil t)
        ("pa" "insert pause" "\\pause" ignore nil t nil)
        ("enu*" "insert enu" "\\begin{enumerate}\n\\item ?\n\\end{enumerate}" cdlatex-position-cursor nil t nil)
        ("it" "insert \\item" "\\item?" cdlatex-position-cursor nil t nil)))

(setq cdlatex-math-modify-alist
         '((?t "\\mathbb" "" t nil nil)))

(setq cdlatex-math-symbol-alist
      '((?0 ("\\varnothing" "\\emptyset"))
        (?1 ("\\ONE" "\\one"))
        (?. ("\\cdot" "\\circ"))
        (?v ("\\vee" "\\bigvee"))
        (?& ("\\wedge" "\\bigwedge"))
        (?9 ("\\cap" "\\bigcap"))
        (?+ ("\\cup" "\\bigcup"))
        (?- ("\\rightharpoonup" "\\hookrightarrow" "\\circlearrowleft"))
        (?= ("\\equiv" "\\Leftrightarrow" "\\Longleftrightarrow"))
        (?~ ("\\sim" "\\approx" "\\propto"))
        (?7 ("\\otimes" "\\bigotimes"))
        (?6 ("\\oplus" "\\bigoplus"))
        (?L ("\\Lambda" "\\lim_{?}^{}" "\\lim\\limits_{?}^{}"))
        (?* ("\\times" "\\prod"))
        (?e ("\\eps" "\\epsilon" "\\exp\\Big( ? \\Big)"))
        (?> ("\\mapsto" "\\longrightarrow" "\\rightrightarrows"))
        (?< ("\\preceq" "\\leftarrow" "\\longleftarrow"))
        (?| ("\\parallel" "\\perp"))
        (?S ("\\Sigma" "\\sum_{?}^{}"))
        (?{ ("\\subset" "\\subseteq"))
        (?} ("\\supset" "\\supseteq"))))
